title: Dr. Sergey Khrapak
logo: /assets/photo_circle.jpg
description: > 
Experienced researcher with 25+ years in theoretical physics, specializing in complex data
analysis, mathematical modeling, and problem-solving. Recently made a deep dive into
data analytics, developing expertise in Python, Power BI, Tableau, SQL, and statistical
analysis to uncover insights and drive data-based decision-making. Feel free to explore and reach out!
# show_downloads = true
theme: jekyll-theme-minimal
