title: Dr. Sergey Khrapak
logo: /Assets/photo_circle.jpg
description: Data Analytics portfolio. Feel free to explore and reach out!
# show_downloads = true
remote_theme: mistakes/minimal-mistakes@latest
