title: Dr. Sergey Khrapak
logo: /Picture2.png
description: Data Analytics portfolio. Feel free to explore and reach out!
# show_downloads = true
theme: jekyll-theme-minimal

author: Sergey Khrapak
email: sergey.khrapak(AT)gmx.de
url: "https://skhrapak.github.io"
