title: Dr. Sergey Khrapak
# logo: /Assets/photo_circle.jpg
# description: Data Analytics portfolio. Feel free to explore and reach out!
# show_downloads = true
description: > Experienced researcher with 25+ years in theoretical physics, specializing in complex data analysis, mathematical modeling, and problem-solving. Recently made a deep dive into data analytics, developing expertise in Python, Power BI, Tableau, SQL, and statistical analysis to uncover insights and drive data-based decision-making
theme: jekyll-theme-minimal

author: Sergey Khrapak
email: sergey.khrapak(AT)gmx.de
url: "https://skhrapak.github.io"
