title: Dr. Sergey Khrapak
# logo: /Assets/photo_circle.jpg
description: Data Analytics portfolio. Includes CV and selected projects. Feel free to explore and reach out!
# show_downloads = true
theme: jekyll-theme-minimal

author: Sergey Khrapak
email: sergey.khrapak(AT)gmx.de
url: "https://skhrapak.github.io"
